#!/usr/bin/env python3

# fuzz_wrap generated: /tmp/wrapped_files/print_781bb636d7825418f19cbc44ab55462959a5c302

import os
import socket
import sys

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

try:
    sock.connect("/tmp/wrap_exe_socket")
    os.dup2(sock.fileno(), sys.stdout.fileno())
    os.dup2(sock.fileno(), sys.stderr.fileno())
except Exception as e:
    print(f"Failed to connect to socket /tmp/wrap_exe_socket: {e}")

calling_args = sys.argv
calling_args[0] = "/tmp/wrapped_files/print_781bb636d7825418f19cbc44ab55462959a5c302"

program_args = [] + calling_args + []
program = program_args[0]
env_vars = os.environ

print(f'running {program_args}')

os.execve(program, program_args, env_vars)
